version: '3.8'

services:
  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_key
      - REACT_APP_GOOGLE_MAPS_API_KEY=your_google_maps_key
    depends_on:
      - backend
    networks:
      - samna-salta-network

  # Backend API (if you have one)
  backend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@db:5432/samna_salta
      - JWT_SECRET=your_jwt_secret_here
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - db
    networks:
      - samna-salta-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=samna_salta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - samna-salta-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - samna-salta-network

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - samna-salta-network

volumes:
  postgres_data:
  redis_data:

networks:
  samna-salta-network:
    driver: bridge 