services:
  # Main Application Service (Docker-based)
  - type: web
    name: samna-salta-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Supabase Database Configuration
      - key: SUPABASE_CONNECTION_STRING
        sync: false
      # Legacy DB vars (for compatibility)
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      # Redis Configuration (optional - can use in-memory fallback)
      - key: REDIS_URL
        sync: false
      # Security
      - key: JWT_SECRET
        sync: false
      # Payment Processing
      - key: STRIPE_SECRET_KEY
        sync: false
      # File Upload (Cloudinary)
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # SMS/Communication (Twilio)
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      # Email (SMTP)
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      # Additional CORS origins
      - key: ADDITIONAL_CORS_ORIGINS
        sync: false
      # Frontend Environment Variables
      - key: REACT_APP_API_URL
        value: https://samna-salta-webapp.onrender.com/api
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        sync: false 