services:
  # Single Web Service (Backend + Frontend)
  - type: web
    name: samna-salta-webapp
    env: node
    plan: free
    rootDir: apps/backend
    buildCommand: npm install && cd ../frontend && npm install && npm run build && cd ../backend && chmod +x start-production.sh
    startCommand: ./start-production.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://samna-salta-webapp.onrender.com
      - key: LOG_LEVEL
        value: info 