services:
  # Frontend Static Site Deployment
  - type: web
    name: samna-salta-frontend
    env: static
    buildCommand: npm install && npm run build:frontend
    staticPublishPath: ./apps/frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API Service
  - type: web
    name: samna-salta-backend
    env: node
    buildCommand: npm install && npm run build:backend
    startCommand: npm run start --workspace=apps/backend
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

  # PostgreSQL Database
  - type: pserv
    name: samna-salta-db
    env: postgres
    plan: free
    ipAllowList: []

  # Redis Cache
  - type: redis
    name: samna-salta-redis
    plan: free
    ipAllowList: [] 