services:
  - type: web
    name: samna-salta-webapp
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://your-backend-api.onrender.com/api
      - key: REACT_APP_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 